version: "3.3"
services:
  pidell:
    dns:
      - ${DNS_MAIN:-1.1.1.1}
      - ${DNS_FALLBACK:-1.0.0.1}
    container_name: pidell
    build: .
    restart: always
    env_file:
      - settings.env
    volumes:
      - pidell_db:/app/data

volumes:
  pidell_db:
